### PR TITLE
Added $previewMaxHeight() and $previewMinHeight() to the disabled view

### PR DESCRIPTION
**Pull request by poldixd**
I added `max-height` and `min-height` to the disabled view. For the scrolling I also added the css class `overflow-y-auto` to the div element.

### CODE REVIEW

**Comment by mohamedsabil83** [comment]
Thanks, @poldixd, for this contribution. It's better to make it enabled by a function or configuration. That way, every dev can display it like now or respect the min/max height.

**Comment by poldixd** [comment]
Yes, that makes sense. Maybe I add two methods like `disabledMaxHeight` and `disabledMinHeight` for the disabled view?

```php
TinyEditor::make('imprint')
    ->maxHeight(200)
    ->disabledMaxHeight(200)
    ->disabled()
    ->columnSpanFull(),
```

**Comment by mohamedsabil83** [comment]
What about `->previewMaxHeight()` and `->previewMinHeight()`?

**Comment by mohamedsabil83** [comment]
Thank you

**Comment by poldixd** [comment]
Thank you for merging and the work on this plugin!

**Pull request merged**
