### PR TITLE
[Added: Plugin] Insert math formulas to TinyMCE Editor

### PR DESCRIPTION
**Pull request by reksmeysrey**
**Screenshots**: 

image

image

### CODE REVIEW

**Comment by mohamedsabil83** [comment]
May add it in the future if requested by many

**Comment by albertobenavides** [comment]
I want this :)

**Comment by mohamedsabil83** [comment]
@albertobenavides, I'll try something on the weekend

**Comment by mohamedsabil83** [comment]
Hi, @albertobenavides. For now, follow this step, and I'll add a feature to toggle that in the next major version.

```php
TinyEditor::make('field_name')
    ->profile('default')
    ->setExternalPlugins([
        'tiny_mce_wiris' => 'https://www.wiris.net/demo/plugins/tiny_mce/plugin.js',
    ]),
```
Publish the package configuration, then add the following to the **default** profile:
- **tiny_mce_wiris** to **Plugins** .
- **tiny_mce_wiris_formulaEditorChemistry** to **tollbar**.

> [!Note]
> You can add a new profile, and put the math plugin on it. Then, when you want it, use `->profile('new_profile')` as mentioned above.

**Comment by albertobenavides** [comment]
This worked! Thank you 🥳

**Pull request closed without merging**
